vetos = {
    "yolomilk": {
        "Sumo Duels",
        "Combo Duels",
        "Speed UHC",
        "PVP Run",
        "Blitz SG",
        "Quakecraft",
        "Smash Heroes",
        "Letter League",
        "Build Battle Pro",
        "Arena Brawl",
    },
    "MrWironic": {
        "VampireZ",
        "Quakecraft",
        "Arena Brawl",
        "Turbo Kart Racers",
        "Sumo Duels",
        "Combo Duels",
        "Boxing Duels",
        "Medium Parkour Speedrun",
        "Housing Parkour",
        "Smash Heroes",
        "Speedrun",
        "Block Shuffle",
        "Build Battle Pro",
        "Chess",
        "Letter League",
    },
    "Riolupro": {
        "Bow Spleef Duels",
        "Bow Duels",
        "Parkour Duels",
        "Speed UHC",
        "Hard Parkour Speedrun",
        "Turbo Kart Racers",
        "Chess",
        "Block Shuffle",
    },
    "KittyCatElite": {
        "Sumo Duels",
        "Combo Duels",
        "Boxing Duels",
        "Block Sumo Duels",
        "Flat Fight",
        "Speedrun",
        "Block Shuffle",
    },
    "Jona": {
        "Murder Mystery Assassins",
        "Murder Mystery Infection",
        "Easy Parkour Speedrun",
        "Medium Parkour Speedrun",
        "Hard Parkour Speedrun",
        "VampireZ",
        "Quakecraft",
        "Arena Brawl",
        "Turbo Kart Racers",
        "Speedrun",
        "Block Shuffle",
        "Smash Heroes",
        "Build Battle Solos",
        "Build Battle Pro",
        "Chess",
        "Letter League",
    },
    "sakapaka1": {
        "NoDebuff Duels",
        "Combo Duels",
        "Boxing Duels",
        "Pearl Fight",
        "Classic Duels",
    },
    "BoggledToggo": {
        "Zombies",
        "SkyWars Duels",
        "Speedrun",
        "BedWars",
        "Speed UHC",
    },
    "lukey": {
        "Murder Mystery Assassins",
        "Murder Mystery Infection",
        "Guess the Build",
        "Boxing Duels",
        "NoDebuff Duels",
    },
    "Frqmes": {"Murder Mystery Infection", "Build Battle Pro"},
    "willy": {
        "Build Battle Solos",
        "Build Battle Pro",
        "Chess",
        "Easy Parkour Speedrun",
        "Medium Parkour Speedrun",
        "Hard Parkour Speedrun",
    },
    "Curiousite": {"Bridge Duels", "Sumo Duels", "Classic Duels", "UHC Duels"},
    "Zuure": {
        "Zombies",
        "Bridge Duels",
        "Blitz SG",
        "Block Sumo",
        "Pixel Party",
        "VampireZ",
        "Turbo Kart Racers",
        "Smash Heroes",
        "Speedrun",
        "Block Shuffle",
        "Build Battle Solos",
        "Build Battle Pro",
        "Letter League",
        "Arena Brawl",
    },
    "ManWithRaft": {"Build Battle Pro"},
}
